Repository wecode-bootcamp-korea/15-1st-Crazytrain-backend, pull requests merged in 2020-12, with the labels that each got.

#2 models.py 초기세팅(table error fix)
  community/migrations/0001_initial.py
  community/models.py
  manage.py
  menu/migrations/0001_initial.py
  menu/models.py
  product/migrations/0001_initial.py
  product/models.py
  user/migrations/0001_initial.py
  user/models.py
Labels: Status: Accepted

#3 [merge 요청] models.py 수정했습니다.
  community/migrations/0001_initial.py
  community/migrations/0002_auto_20201217_0945.py
  community/models.py
  community/views.py
  menu/migrations/0001_initial.py
  product/migrations/0001_initial.py
  user/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#7 [수정] models.py 수정요청
  community/migrations/0001_initial.py
  community/migrations/0002_auto_20201217_0945.py
  community/models.py
  menu/migrations/0001_initial.py
  product/migrations/0001_initial.py
  product/models.py
  user/migrations/0001_initial.py
  user/models.py
Labels: Status: 리뷰 요청

#8 [오늘의집]models.py수정본
  community/models.py
  review/__init__.py
  review/admin.py
  review/apps.py
  review/migrations/__init__.py
  review/models.py
  review/tests.py
  review/views.py
  shoppingcart/__init__.py
  shoppingcart/admin.py
  shoppingcart/apps.py
  shoppingcart/migrations/__init__.py
  shoppingcart/models.py
  shoppingcart/tests.py
  shoppingcart/views.py
  todayhouse/settings.py
  user/models.py
Labels: Status: 리뷰 요청

#4 [오늘의집] 석여주 - 회원가입 엔드포인트 작성
  todayhouse/urls.py
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#5 [오늘의 집] 이수한 - 스토어 카테고리 사이드바 api 작성 (피드백 반영)
  menu/urls.py
  menu/views.py
  review/models.py
  shoppingcart/models.py
  todayhouse/settings.py
  todayhouse/urls.py
  user/views.py
Labels: Status: 컨플릭트 해결 요청

#6 [오늘의집]석여주 - 로그인 엔드포인트 구현완료
  user/models.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: Accepted

#9 [오늘의집] 장바구니에 추가/조회 앤드포인트 작성(리뷰수정반영)
  community/migrations/0002_auto_20201221_1852.py
  review/migrations/0001_initial.py
  shoppingcart/migrations/0001_initial.py
  shoppingcart/migrations/0002_auto_20201222_1049.py
  shoppingcart/models.py
  shoppingcart/urls.py
  shoppingcart/views.py
  todayhouse/urls.py
  user/utils.py
  user/views.py
Labels: Status: 리뷰 요청

#11 [오늘의집] 장바구니 수량변경 앤드포인트 작성
  product/migrations/0002_auto_20201223_0650.py
  product/models.py
  shoppingcart/migrations/0003_remove_cart_size.py
  shoppingcart/models.py
  shoppingcart/views.py
  todayhouse/settings.py
Labels: Status: Accepted

#12 [오늘의집] models.py일부 수정
  product/models.py
Labels: Status: 리뷰 요청

#13 [오늘의집] 장바구니 상품업데이트 관련 일부 수정
  shoppingcart/urls.py
  shoppingcart/views.py
  user/views.py
Labels: Status: 리뷰 요청

#14 [오늘의집]장바구니 관련 최종수정
  product/migrations/0003_auto_20201223_1817.py
  shoppingcart/migrations/0004_auto_20201223_1817.py
  shoppingcart/models.py
  shoppingcart/views.py
  user/views.py
Labels: Status: 리뷰 요청

#15 [오늘의집]상품리스트 및 상품상세페이지 API완료
  community/migrations/0001_initial.py
  menu/migrations/0001_initial.py
  menu/urls.py
  product/migrations/0001_initial.py
  product/models.py
  product/urls.py
  product/views.py
  review/migrations/0001_initial.py
  shoppingcart/migrations/0001_initial.py
  shoppingcart/migrations/0002_auto_20201222_1049.py
  shoppingcart/migrations/0003_remove_cart_size.py
  todayhouse/urls.py
  user/migrations/0001_initial.py
Labels: Status: Accepted

#16 [오늘의집] 상품 내역 뷰 수정
  product/views.py
Labels: Status: 리뷰 요청

#10 [오늘의집] Community 엔드포인트 구현 & 리뷰 반영
  community/migrations/0003_remove_post_product.py
  community/models.py
  community/urls.py
  community/views.py
  product/migrations/0002_auto_20201223_1157.py
  product/views.py
  shoppingcart/migrations/0004_auto_20201223_1817.py
  todayhouse/urls.py
Labels: Status: 리뷰 요청

#17 [오늘의집]장바구니 업데이트 관련 경로 수정
  shoppingcart/views.py
Labels: Status: 리뷰 요청
